### ISSUE TITLE
Duplicate green cards

### ISSUE THREAD

**Issue by blindawson** [alpacafondue/tts_crew#1]
We've played through a dozen or so hands in a 3-player game and we noticed two green 6's and two green 2's were dealt to us. We then noticed we were each dealt 11 cards total so there seems to be a third duplicate hiding somewhere as well. Not sure if this error was occurring in earlier hands or not. Besides those small bugs thanks for the great mod! We're really enjoying it!

**Comment by alpacafondue** [comment]
I ran into a similar situation once. I think it's a TTS bug outside of what my code is doing, perhaps with delayed frames. My recommendation would be to reload the mod if using the Reset button causes issues.
